package com.timebasedfitness.app.ui.settings

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.timebasedfitness.app.ui.theme.AppSpacing

@Composable
fun PlanTransferScreen(
    viewModel: SettingsViewModel,
    onBack: () -> Unit,
    onShare: (String) -> Unit
) {
    var jsonText by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }
    Column(
        modifier = Modifier.fillMaxSize().padding(AppSpacing.marginPage),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        TextButton(onClick = onBack) { Text("Back") }
        Text("Import or share a plan", style = MaterialTheme.typography.headlineMedium)
        Text("Paste a JSON plan generated by any AI, or share your current routines.", style = MaterialTheme.typography.bodyMedium)
        OutlinedTextField(
            value = jsonText,
            onValueChange = { newValue ->
                // Cap paste size to avoid OOM/DoS via a huge pasted string. 64 KB is
                // generously above any plausible plan (codec caps each step at 500 chars,
                // 4 categories * 100 steps * 500 chars ≈ 200 KB worst case, but realistic
                // plans are a few KB). Anything larger is rejected at input time.
                if (newValue.length <= MAX_PASTED_JSON_CHARS) {
                    jsonText = newValue
                    error = null
                } else {
                    error = "Plan is too large (max $MAX_PASTED_JSON_CHARS characters)."
                }
            },
            modifier = Modifier.fillMaxWidth().weight(1f),
            label = { Text("Plan JSON") }
        )
        error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
        Button(
            onClick = {
                if (jsonText.length > MAX_PASTED_JSON_CHARS) {
                    error = "Plan is too large (max $MAX_PASTED_JSON_CHARS characters)."
                } else {
                    viewModel.importPlan(jsonText) { error = it ?: run { jsonText = ""; onBack(); null } }
                }
            },
            modifier = Modifier.fillMaxWidth()
        ) { Text("Import plan") }
        TextButton(
            onClick = { viewModel.exportPlan(onShare) },
            modifier = Modifier.fillMaxWidth()
        ) { Text("Share current plan") }
    }
}

// 64 KB cap on pasted JSON. The codec's validator bounds each field, so any well-formed
// plan is well below this. The cap protects the device from OOM if a user pastes a
// pathological payload.
private const val MAX_PASTED_JSON_CHARS = 64 * 1024
