package com.timebasedfitness.app.ui.settings

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.timebasedfitness.app.ui.theme.AppSpacing

import android.widget.Toast
import androidx.compose.ui.platform.LocalContext

import androidx.compose.material3.AlertDialog
import androidx.compose.material3.OutlinedButton
import androidx.compose.runtime.collectAsState

@Composable
fun PlanTransferScreen(
    viewModel: SettingsViewModel,
    onBack: () -> Unit,
    onShare: (String) -> Unit
) {
    val context = LocalContext.current
    val uiState by viewModel.uiState.collectAsState()
    var jsonText by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }

    // Validation & Preview Dialog
    uiState.pendingPlanPreview?.let { previewPlan ->
        AlertDialog(
            onDismissRequest = { viewModel.clearPreview() },
            title = { Text("Preview: ${previewPlan.title}") },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text("Found ${previewPlan.categories.size} categories:", style = MaterialTheme.typography.labelMedium)
                    previewPlan.categories.forEach { cat ->
                        val timeStr = if (cat.startTime != null && cat.endTime != null) " (${cat.startTime} – ${cat.endTime})" else ""
                        val goalStr = cat.goal?.let { " • $it" } ?: ""
                        Text(
                            "• ${cat.category}: ${cat.title}$timeStr (${cat.steps.size} steps$goalStr)",
                            style = MaterialTheme.typography.bodySmall
                        )
                    }
                    Text("Apply this plan to your routines?", style = MaterialTheme.typography.bodySmall)
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        viewModel.confirmImportPendingPlan { err ->
                            if (err != null) {
                                error = err
                            } else {
                                Toast.makeText(context, "Plan imported successfully", Toast.LENGTH_SHORT).show()
                                jsonText = ""
                                onBack()
                            }
                        }
                    }
                ) {
                    Text("Confirm & Apply")
                }
            },
            dismissButton = {
                TextButton(onClick = { viewModel.clearPreview() }) {
                    Text("Cancel")
                }
            }
        )
    }

    Column(
        modifier = Modifier.fillMaxSize().padding(AppSpacing.marginPage),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        TextButton(onClick = onBack) { Text("Back") }
        Text("Import or share a plan", style = MaterialTheme.typography.headlineMedium)
        Text("Paste a JSON plan generated by any AI, or share your current routines.", style = MaterialTheme.typography.bodyMedium)
        OutlinedTextField(
            value = jsonText,
            onValueChange = { newValue ->
                if (newValue.length <= MAX_PASTED_JSON_CHARS) {
                    jsonText = newValue
                    error = null
                } else {
                    error = "Plan is too large (max $MAX_PASTED_JSON_CHARS characters)."
                }
            },
            modifier = Modifier.fillMaxWidth().weight(1f),
            label = { Text("Plan JSON (Auto-repairs markdown & quotes)") }
        )
        error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
        Button(
            onClick = {
                if (jsonText.length > MAX_PASTED_JSON_CHARS) {
                    error = "Plan is too large (max $MAX_PASTED_JSON_CHARS characters)."
                } else {
                    viewModel.previewPlan(jsonText) { err ->
                        if (err != null) error = err
                    }
                }
            },
            modifier = Modifier.fillMaxWidth()
        ) { Text("Preview & Import Plan") }

        if (uiState.canUndoImport) {
            OutlinedButton(
                onClick = {
                    viewModel.undoLastImport { err ->
                        if (err != null) {
                            Toast.makeText(context, "Undo failed: $err", Toast.LENGTH_SHORT).show()
                        } else {
                            Toast.makeText(context, "Restored previous plan", Toast.LENGTH_SHORT).show()
                        }
                    }
                },
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("↩ Undo Last Import")
            }
        }

        TextButton(
            onClick = { viewModel.exportPlan(onShare) },
            modifier = Modifier.fillMaxWidth()
        ) { Text("Share current plan") }
    }
}

// 64 KB cap on pasted JSON. The codec's validator bounds each field, so any well-formed
// plan is well below this. The cap protects the device from OOM if a user pastes a
// pathological payload.
private const val MAX_PASTED_JSON_CHARS = 64 * 1024
