package com.timebasedfitness.app.ui.settings

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.timebasedfitness.app.ui.theme.AppSpacing

@Composable
fun PlanTransferScreen(
    viewModel: SettingsViewModel,
    onBack: () -> Unit,
    onShare: (String) -> Unit
) {
    var jsonText by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }
    Column(
        modifier = Modifier.fillMaxSize().padding(AppSpacing.marginPage),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        TextButton(onClick = onBack) { Text("Back") }
        Text("Import or share a plan", style = MaterialTheme.typography.headlineMedium)
        Text("Paste a JSON plan generated by any AI, or share your current routines.", style = MaterialTheme.typography.bodyMedium)
        OutlinedTextField(
            value = jsonText,
            onValueChange = { jsonText = it; error = null },
            modifier = Modifier.fillMaxWidth().weight(1f),
            label = { Text("Plan JSON") }
        )
        error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
        Button(
            onClick = { viewModel.importPlan(jsonText) { error = it ?: run { jsonText = ""; onBack(); null } } },
            modifier = Modifier.fillMaxWidth()
        ) { Text("Import plan") }
        TextButton(
            onClick = { viewModel.exportPlan(onShare) },
            modifier = Modifier.fillMaxWidth()
        ) { Text("Share current plan") }
    }
}
